import os
import json
from datetime import datetime
from google import genai
from google.genai import types

# IMPORTANT: KEEP THIS COMMENT - using blueprint:python_gemini
# Note that the newest Gemini model series is "gemini-2.5-flash" or "gemini-2.5-pro"
# do not change this unless explicitly requested by the user
GEMINI_API_KEY = os.environ.get("GEMINI_FREE_API_KEY") or os.environ.get("GEMINI_API_KEY")
client = genai.Client(api_key=GEMINI_API_KEY)

def summarize_agent(top_updates, founder_persona="Startup Founder"):
    """
    Summarization Agent: Generates beautiful Markdown digest with emojis, headlines,
    insights, and actionable "Founder Takeaway".
    """
    print("📝 Summarization Agent: Generating digest...")
    
    # Prepare context for AI
    updates_summary = []
    for i, update in enumerate(top_updates, 1):
        competitor_cat = update.get('competitor_category', 'Unknown')
        source = update.get('source', 'N/A')
        source_type = update.get('source_type', 'N/A')
        
        updates_summary.append(f"""
        Update #{i}:
        Competitor: {update['competitor']} ({competitor_cat})
        Category: {update.get('category', 'N/A')}
        Source: {source} ({source_type})
        Priority Score: {update.get('priority_score', 0)}/10
        Urgency: {update.get('urgency_level', 'N/A')}
        Update: {update.get('original_update', update.get('update', 'N/A'))}
        Strategic Implication: {update.get('strategic_implication', 'N/A')}
        Impact Areas: {', '.join(update.get('impact_areas', []))}
        """)
    
    prompt = f"""
    Create a beautiful, actionable weekly digest for a startup founder based on these top 3 competitor updates.
    
    {chr(10).join(updates_summary)}
    
    Generate a compelling digest with:
    1. A catchy headline for each update with appropriate emoji
    2. Competitor category badge (Direct Competitor, Market Leader, Emerging Threat, or Adjacent Player)
    3. Brief but insightful summary (2-3 sentences max per update)
    4. Source attribution (where this intel came from)
    5. Clear category indicator (Product/Pricing/Marketing)
    6. A strategic "Founder Takeaway" section at the end with specific next actions
    
    Make it:
    - Actionable and business-focused for startup founders
    - Easy to scan (use emojis and clear formatting)
    - Strategic (what should the founder do about this?)
    - Include competitor categorization to help founders prioritize
    
    Format in clean, readable markdown. Use emojis to make it engaging but professional.
    Do NOT include the title "CompetitiveRadar – Weekly Digest" as that will be added separately.
    """
    
    try:
        response = client.models.generate_content(
            model="gemini-2.5-pro",
            contents=[
                types.Content(role="user", parts=[types.Part(text=prompt)])
            ],
            config=types.GenerateContentConfig(
                system_instruction="You are an expert business strategist creating executive briefings for startup founders. Your summaries are concise, actionable, and strategically insightful."
            )
        )
        
        digest_content = response.text
        
        # Create full digest with header
        current_date = datetime.now().strftime("%B %d, %Y")
        
        full_digest = f"""# 🧭 CompetitiveRadar – Weekly Digest
**For:** {founder_persona} | **Date:** {current_date}

---

{digest_content}

---

*Generated by CompetitiveRadar Agentic AI System*
"""
        
        print("✅ Summarization Agent: Digest generated successfully")
        return full_digest
        
    except Exception as e:
        print(f"Error generating digest: {e}")
        return f"# Error generating digest\n\nAn error occurred: {str(e)}"
